hallpass/hallpass/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

urlpatterns = [
    
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('logout', LogoutView.as_view(), name="logout"),
    path('logout/',
    auth_views.LogoutView.as_view(
        template_name='registration/logged_out.html',
        next_page=None
    ),
    name = 'logout'
),
    path('', include('passes.urls')),
    # All auth urls
    path('accounts/', include('allauth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hallpass/passes/urls.py
from django.urls import path, include
from . import views
from . import views_static as vs

urlpatterns = [
    # home page
    path("", vs.home, name='home'),

    # Sign in form
    path('sign-in', vs.sign_in, name='sign_in'),

    # Major User features
    path('dashboard', views.dashboard, name='dashboard'),
    path('monitor_destinations', views.monitor_destinations, name='monitor'),
    path("time_out", views.time_out, name='time_out'),
    path("time_in", views.time_in, name='time_in'),
    path("change_location", views.change_location, name='change_location'),

    # Static Pages required for OAuth and SEO
    path('about/', vs.about, name='about'),
    path('contact/', vs.contact, name='contact'),
    path('help/', vs.help, name='help'),
    path('robots.txt', vs.robots, name='robots'),
    path('privacy/', vs.privacy, name='privacy'),
    path('terms/', vs.terms, name='terms'),

]

hallpass/passes/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timezone
from django.db.models.signals import post_save
from django.dispatch import receiver

class Building(models.Model):
    building = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.building}"

class Category(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=7, default='#eeeeee')
    text_color = models.CharField(max_length=7, default='#000000')
    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
         return f"{self.name} "

class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    student_id = models.CharField(max_length=100, unique=True)
    building = models.ForeignKey(Building, null=True, on_delete=models.SET_NULL)

    def __str__(self):
         return f"{self.first_name} {self.last_name}, Id: {self.student_id}"

class Destination(models.Model):
    building = models.ForeignKey(Building, null=True, on_delete=models.SET_NULL)
    room = models.CharField(max_length=100)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    max_people_allowed = models.PositiveIntegerField(default = 2)

    # for p in Destination.objects.raw("SELECT * FROM passes_destination"):
    #     print(p)

    def __str__(self):
         if (self.category):
            return f"{self.room} {self.category.name}"
         return f"{self.room} Genderless" 

class HallPass(models.Model):
    time_in = models.DateTimeField(blank=True, null=True)
    time_out = models.DateTimeField(blank=True, null=True)
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    destination = models.ForeignKey(Destination, null=True, on_delete=models.SET_NULL)
    building = models.ForeignKey(Building, null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    arrival_time = models.DateTimeField(auto_now=True)
    forgot_time_out = models.BooleanField(default=False)

    
    class Meta:
        verbose_name_plural = "hall passes"
        permissions = (("can_view_log_history", "can_edit_log_history"),)

    def __str__(self): 
           
            return f"Teacher: {self.user}, Destination: {self.destination}, Student: {self.student_id}, Time_in: {self.time_in}, Time_out: {self.time_out}, Arrival_time: {self.arrival_time}"

class Profile(models.Model):
    destinations = models.ManyToManyField(Destination, blank=True)
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    building = models.ForeignKey(Building, null=True, on_delete=models.SET_NULL)
    queue = models.BooleanField(default=True, verbose_name="Enable Queue")

    def __str__(self):
        return f"{self.user}, {self.building},"

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

hallpass/passes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Student, HallPass, Destination, Category, Profile
from django.forms.widgets import TextInput
from django.core.exceptions import ValidationError
from django_toggle_switch_widget.widgets import DjangoToggleSwitchWidget


class LogForm(forms.Form):
    log_id = forms.CharField() # This is all we need to get cleaned_data from the form

class LocationForm(forms.Form):
    log_id = forms.CharField() # This is all we need to get cleaned_data from the form
    destination_id = forms.CharField() # This is all we need to get cleaned_data from the form


    
class ArrivalForm(forms.Form):
    student_id = forms.CharField(max_length=6)
    destination_id = forms.CharField() # This is all we need to get cleaned_data from the form
    
    # This function contains the custom validation 
    # for the student_if field
    def clean_student_id(self):
        input_id = self.cleaned_data["student_id"]
        id_length = len(input_id)
        validate = []

        if id_length != 6:
            validate.append("IDs must be 6 numbers")
            
        if not input_id.isnumeric():
            validate.append("IDs cannot contain letters")

        if not Student.objects.filter(student_id=input_id).exists():
            validate.append("This ID is not in our system.")

        # We can let kids go to the 
        # bathroom if they are from another school 
        # if student_query[0].building != self.request.user.profile.building:
        #     validate += "Student must belong to current building"
            
        if (len(validate) > 0):
            raise ValidationError(validate)

        return input_id
    
class ProfileForm(forms.ModelForm):
    destinations_choices = None
    destinations = forms.ModelMultipleChoiceField(
        label='Destinations', 
        queryset=destinations_choices, 
        required=False, 
        widget=forms.CheckboxSelectMultiple()
    )
    destinations.widget.template_name = 'widgets/destination_choices.html'

    class Meta:
        model = Profile
        fields = ('building','destinations','queue')
        widgets = {
            'building': forms.Select(attrs={'onchange':'this.form.submit()'}),
            'queue': forms.CheckboxInput(attrs={"class": "form-check-input", "id": "flexSwitchCheckChecked"})
             # This isn't best practice. We should use JS for this.
        }

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        # Order_by sorts the choices by alpha.
        self.destinations_choices = Destination.objects.filter(building = self.instance.building).order_by('room', 'category')
        self.fields['destinations'].queryset = self.destinations_choices
        self.fields['building'].label="Buildings"


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'color': TextInput(attrs={'type': 'color'}),
            'text_color': TextInput(attrs={'type': 'color'}),
        }

class ContactForm(forms.Form):
    name = forms.CharField(max_length=128)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea())

hallpass/passes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .forms import *
from .models import Student, HallPass, Destination
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.views.decorators.http import require_http_methods
import datetime
import string
from django.views.decorators.http import require_http_methods



@login_required
@require_http_methods(["POST"])
def time_in(request):
    form = LogForm(request.POST)
    if form.is_valid():
        log_id = form.cleaned_data['log_id']
        log = get_object_or_404(HallPass, pk = log_id)
        if log.time_in:
            return redirect("monitor")
        log.time_in = datetime.datetime.now()
        log.save()
    return redirect("monitor")

@login_required
@require_http_methods(["POST"])
def change_location(request):
    form = LocationForm(request.POST)
    if form.is_valid():
        log_id = form.cleaned_data['log_id']
        destination_id = form.cleaned_data['destination_id']

        log = get_object_or_404(HallPass, pk = log_id)
        destination = get_object_or_404(Destination, pk = destination_id)
        log.destination = destination
        log.save()
    return redirect("monitor")

@login_required
@require_http_methods(["POST"])
def time_out(request):
    form = LogForm(request.POST)
    if form.is_valid():
        log_id = form.cleaned_data['log_id']
        log = get_object_or_404(HallPass, pk = log_id)
        # check to makes sure they haven't been signed out at another computer
        if log.time_out == None:
            log.time_out = datetime.datetime.now()
            log.save()
        # Check to see if we can time_in the next person in queue
        destination = log.destination
        max = destination.max_people_allowed
        count_in = len(HallPass.objects.filter(destination = destination).exclude(time_in = None).filter(time_out = None))
        count_waiting = len(HallPass.objects.filter(destination = destination).filter(time_in = None).filter(time_out = None))
        if count_in < max and count_waiting > 0:
            next_in_line = HallPass.objects.filter(destination = destination).filter(time_in = None).filter(time_out = None)[0]
            next_in_line.time_in = datetime.datetime.now()
            next_in_line.save()
    
    return redirect("monitor")

@login_required
def monitor_destinations(request):
    # Users must have selected destinations 
    # in their profile. If not, redirect user
    user_profile = request.user.profile
    user_destinations = user_profile.destinations.filter(building = user_profile.building).order_by('room', 'category')
    if not user_destinations:
        return redirect(reverse('dashboard'))
    
    # Set form
    arrival_form = ArrivalForm()

    # Deal with submitted arrival form
    if request.method == "POST":
        arrival_form = ArrivalForm(request.POST)
        if arrival_form.is_valid():
            student_id = arrival_form.cleaned_data['student_id']

            # Retrieve the student from the database
            if (Student.objects.filter(student_id = student_id).exists()):
                student = get_object_or_404(Student, student_id = student_id)
                # check to see if student forgot to log out
                logs = HallPass.objects.filter(student_id = student).filter(time_out = None)
                for l in logs:
                    l.time_out = datetime.datetime.now() # logs student out 
                    l.forgot_time_out = True
                    l.save()
                # makes a new log
                destination_id = arrival_form.cleaned_data['destination_id']
                destination = get_object_or_404(Destination, pk = destination_id)
                log = HallPass(
                    student_id = student,
                    destination = destination,
                    building = destination.building,
                    arrival_time = datetime.datetime.now(),
                    user = request.user,
                )
                # I'VE TEMP DISABLED THIS FOR USER TESTING
                # Check if MAX_ALLOWED has been met yet. If not, time_in immediately
                queue = Profile.objects.filter(user = request.user)[0].queue
                if queue:
                    max = destination.max_people_allowed
                    count_in = len(HallPass.objects.filter(destination = destination).exclude(time_in = None).filter(time_out = None))
                    if count_in < max:
                        log.time_in = datetime.datetime.now()

                log.save()
                # Log created successfully. Reset the form
                arrival_form = ArrivalForm()
                
    # Prepare the data for the template
    destination_data = []
    for destination in user_destinations:
        logs = HallPass.objects.filter(destination = destination).filter(time_out = None)
        destination_data.append(
            {
                "destination": destination,
                "logs": logs,
                "people_in": len(HallPass.objects.filter(destination = destination).exclude(time_in = None).filter(time_out = None)),
                "queue": len(HallPass.objects.filter(destination = destination).filter(time_out = None)) - len(HallPass.objects.filter(destination = destination).exclude(time_in = None).filter(time_out = None)),
            }
        )
    return render(
        request,
        'pages/monitor_destinations.html',
        {
            'arrival_form': arrival_form,
            'profile': user_profile,
            'destination_data': destination_data,
        }
    )


@login_required
def dashboard(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=request.user.profile)

        if profile_form.is_valid():
            profile_form.save()
            return redirect(reverse('monitor'))
    else:
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'pages/dashboard.html', { 'form': profile_form,})

hallpass/passes/templates/pages/contact.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}Contact{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <h2>Contact Us</h2>
    </div>
    <div class="row">
        <form action="" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Submit
            </button>
            {% endbuttons %}
        </form>
    </div>
</div>
{% endblock %}

hallpass/passes/templates/pages/dashboard.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
<div class="dashboard">
  <h1> Select Destinations </h1>

  <div>
    <form action="" method="post" id="destination-form">
      {% csrf_token %}
      <hr>
      <div>
        <h2>Building</h2>
        {% bootstrap_form form exclude='destinations,queue' %}
      </div>
      <hr>
      <div>
        <h2>Destinations</h2>
        {% bootstrap_form form exclude='building,queue' %}
      </div>
      <hr>
      <div class="form-check form-switch">
        <h2>Queue</h2>
        <div class="ms-4 p-0">
          {% bootstrap_form form exclude='building, destinations' %}

        </div>
      </div>
      <hr>
      <input type='hidden' name='next' value='{{ next }}'>
      {% buttons %}
      <button type="submit" class="btn btn-primary">
        Monitor
      </button>
      {% endbuttons %}
    </form>
  </div>
</div>

{% endblock %}

hallpass/passes/templates/pages/help.html
{% extends 'base.html' %}

{% block title %}Help{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <h2>Help</h2>
    </div>
    <div class="row">
        <p>For assistance with this app, please see your administrator.</p>
    </div>
</div>
    
{% endblock %}

hallpass/passes/templates/pages/monitor_destinations.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
{% load static %}

<div class="monitor row">
    <section class="student-sign-in">

        <form id="student-field" method="POST" autocomplete="off" class="student-sign-in-form">
            {% csrf_token %}
            <div class="id-input">
                <h1>{{ profile.building }}</h1>
                {% bootstrap_form arrival_form exclude="destination_id" %}
            </div>
            <input type="hidden" name="arrival">
            <div class="mb-3 notice">
                <small>*If a student should be in the system, please contact <a
                        href="mailto:leboeufj@worcesterschools.net?subject=HallPass Request - Add student">leboeufj@worcesterschools.net</a>
                    with the name and ID of the student.</small>
            </div>
            <div class="button-group">
                {{ field.errors }}
                {% for queue in destination_data %}
                <button name="destination_id" value="{{ queue.destination.id }}" form="student-field"
                    class="btn btn-secondary mx-3"
                    style="background-color: {{ queue.destination.category.color }}; color:{{ queue.destination.category.text_color }}  ">
                    {{ queue.destination.category }}</button>
                {% endfor %}
            </div>
        </form>
    </section>

    <section class="monitor-destinations" style="grid-template-columns: repeat({{ destination_data|length }}, 350px);">
        {% if destination_data %}
        {% for queue in destination_data %}
        <aside class="destination">
            <div class="destination-heading" style="color: {{ queue.destination.category.color }};">
                <h2>{{ queue.destination }}</h2>
                <div class="labels">
                    <em class="max">Max {{ queue.destination.max_people_allowed }}</em>
                    <em class="in">In {{ queue.people_in }}</em>
                    <em class="waiting">Waiting {{ queue.queue }}</em>
                </div>
            </div>
            <hr>
            <section class="destination-body">
                {% for log in queue.logs %}
                {% if not log.time_in %}
                <div class="destination-log-disabled">
                    <div class="student">{{ log.student_id }}</div>
                    <div class="time-in">Arrival Time: {{ log.Arrival_time|date:"h:i A" }}</div>
                    <div class="timer-display"> &nbsp; </div>
                    <div class="start-time" hidden>{{ log.arrival_time.isoformat }}</div>
                    <footer class="d-flex flex-wrap justify-content-around align-items-end">

                        <form action="{% url 'time_in' %}" method="POST" class="flex-grow-1 px-1">
                            {% csrf_token %}
                            <button class="btn btn-primary" style="width:100%" name="log_id" value="{{ log.id }}">
                                Time In
                            </button>
                        </form>
                        <form action="{% url 'time_out' %}" method="POST" class="flex-grow-1 px-1">
                            {% csrf_token %}
                            <button class="btn btn-danger" style="width:100%" name="log_id" value="{{ log.id }}">
                                Cancel
                            </button>
                        </form>
                        <form action="{% url 'change_location' %}" method="POST" class="flex-grow-1 px-1 mt-2"
                            style="width:100%">
                            {% csrf_token %}
                            <div class="input-group">
                                <select class="form-select" id="inputGroupSelect02" name="destination_id">
                                    <option selected>Move to...</option>
                                    {% for queue in destination_data %}
                                    <option value="{{ queue.destination.id }}">{{ queue.destination }}</option>
                                    {% endfor %}
                                </select>
                                <button class="btn btn-secondary" type="submit" name="log_id"
                                    value="{{ log.id }}">Go</button>
                            </div>
                        </form>
                    </footer>
                </div>
                {% else %}
                <div class="destination-log" style="background-color: {{ queue.destination.category.color }};">
                    <div class="student">{{ log.student_id }}</div>
                    <div class="time-in">Time In: {{ log.time_in|date:"h:i A" }}</div>
                    <div class="timer-display"> &nbsp; </div>
                    <div class="start-time" hidden>{{ log.time_in|date:'Y-m-d H:i:s'}}</div>
                    <footer class="d-flex flex-wrap justify-content-around align-items-end">
                        <form action="{% url 'time_out' %}" method="POST" class="flex-grow-1 px-1">
                            {% csrf_token %}
                            <button class="btn btn-primary" style="width:50%" name="log_id" value="{{ log.id }}">
                                Time Out
                            </button>
                        </form>
                        <form action="{% url 'change_location' %}" method="POST" class="flex-grow-1 px-1 mt-2"
                            style="width:100%">
                            {% csrf_token %}
                            <div class="input-group">
                                <select class="form-select" id="inputGroupSelect02" name="destination_id">
                                    <option selected>Move to...</option>
                                    {% for queue in destination_data %}
                                    <option value="{{ queue.destination.id }}">{{ queue.destination }}</option>
                                    {% endfor %}
                                </select>
                                <button class="btn btn-secondary" type="submit" name="log_id"
                                    value="{{ log.id }}">Go</button>
                            </div>
                        </form>
                    </footer>
                </div>
                {% endif %}
                {% endfor %}
            </section>
        </aside>
        {% endfor %}
        {% endif %}
    </section>

</div><!-- /monitor -->

{% block scripts %}
<script>
    // set focus on arrival form every time
    document.querySelector('#id_student_id').focus();

    logs = document.querySelectorAll(".destination-log");
    minutesUntilWarning = 5;
    setInterval(() => {
        logs.forEach(log => {

            let display = log.querySelector(".timer-display");
            let startTime = log.querySelector(".start-time");

            let deltaMilliseconds = new Date() - new Date(startTime.innerHTML);
            display.innerHTML = millisecondsToStopWatch(deltaMilliseconds);

            if (deltaMilliseconds > 1000 * 60 * minutesUntilWarning && !log.classList.contains('stopwatch-warning')) {
                log.classList.add('stopwatch-warning');
                console.log(log)
            }
        })
    }, 10);

    // function formatDate(difference) {
    //     let hours = Math.floor((difference % (1000 * 60 * 60 * 60)) / (1000 * 60 * 60));
    //     let minutes = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60));
    //     let seconds = Math.floor((difference % (1000 * 60)) / 1000);
    //     return [
    //         hours.toString().padStart(2, '0'),
    //         minutes.toString().padStart(2, '0'), 
    //         seconds.toString().padStart(2, '0'), 
    //     ];
    // }
    function millisecondsToStopWatch(milliseconds) {
        time = []
        // time units in milliseconds
        s = 1000;
        m = 60 * s;
        h = 60 * m;
        d = 24 * h;
        conversions = [d, h, m, s];
        // get the number of days
        conversions.forEach(t => {
            elapsed = Math.floor(milliseconds / t);
            if (elapsed > 0 || time.length > 0) {
                time.push(elapsed);
                // remove the time elapsed from milliseconds
                milliseconds -= elapsed * t
            }
        })
        if (time.length > 1) {
            return time.map(el => el.toString().padStart(2, '0')).join(':');
        }
        if (time.length > 0) {
            return `:${time[0]?.toString().padStart(2, '0')}`;
        }
        return ":00";
    }

    /**
     * Append student id to contact email link. 
     * This will auto insert any student ID that has been typed in the input field
     * into the email href string for the subject.
     */
    const contactEmail = document.querySelector('.notice a');
    let emailString = contactEmail.href;
    document.querySelector('#id_student_id').addEventListener('input', (e) => {
        let inputId = e.target.value;
        contactEmail.href = `${emailString} ID: ${inputId}`;
    })
</script>
{% endblock %}
{% endblock %}